### ISSUE TITLE
Error download distribution 

### ISSUE THREAD

**Issue by TokyoghoulEs** [jorexdeveloper/Install-NetHunter-Termux#1]
[*] Checking package dependencies...
[=] wget is OK                                  [=] proot is OK                                 [=] tar is OK
[=] pulseaudio is OK

  [1] NetHunter ARM64 (full)

  [2] NetHunter ARM64 (mini)                                                                      [3] NetHunter ARM64 (nano)

[*] Enter the image you want to install: 3      [=] Nano selected

[*] Verifying integrity of rootfs archive...
[!] Rootfs corrupted. Please run this installer again or download the file manually.
~/proot-distro $

**Comment by jorexdeveloper** [comment]
Fixed the issue and also made a few changes....everything should work fine now.
