### ISSUE TITLE
chmod: cannot access '/data/data/com.termux/files/home/bin/nethunter': No such file or directory

### ISSUE THREAD

**Issue by TokyoghoulEs** [jorexdeveloper/Install-NetHunter-Termux#2]
╻┏ ┏━┓╻  ╻   ┏┓╻┏━╸╺┳╸╻ ╻╻ ╻┏┓╻╺┳╸┏━╸┏━┓
        ┣┻┓┣━┫┃  ┃╺━╸┃┗┫┣╸  ┃ ┣━┫┃ ┃┃┗┫ ┃ ┣╸ ┣┳┛        ╹ ╹╹ ╹┗━╸╹   ╹ ╹┗━╸ ╹ ╹ ╹┗━┛╹ ╹ ╹ ┗━╸╹┗╸
                        by Jore

[*] Beginning installation process.

[*] Checking device architecture...

[*] Checking package dependencies...
[=] wget is OK
[=] proot is OK
[=] tar is OK
[=] pulseaudio is OK

  [1] NetHunter ARM64 (full)

  [2] NetHunter ARM64 (mini)

  [3] NetHunter ARM64 (nano)                    
[*] Enter the image you want to install: 1
[=] Full selected

[?] Existing rootfs directory found. Delete and create a new one? y/N: y
[!] Deleting rootfs directory...

[?] Existing image file found. Delete and download a new one. y/N: n
[!] Using existing rootfs archive

[*] Verifying integrity of rootfs archive...

[*] Extracting rootfs...
install-nethunter.sh: line 188: /data/data/com.termux/files/home/bin/nethunter: No such file or directory
chmod: cannot access '/data/data/com.termux/files/home/bin/nethunter': No such file or directory
ln: failed to create symbolic link '/data/data/com.termux/files/home/bin/nh': No such file or directory

[*] Making some tweaks.

[*] Granting root permissions to user kali.
[=] Done.

[*] Preventing creation of links in read only file system.
[=] Done.

[*] Setting static display for the system.
[=] Done.

[*] Settting pulse audio server.
[=] Done.

[*] Setting DNS settings.
[=] Done.

[*] Setting up jdk variables.
[=] Done.

[?] Set default shell for user kali. y/N: n

[?] Set UID and GID for user kali to match that of Termux. y/N: n

[?] Set Time Zone and Local Time. y/N: n

[*] Installation process complete.

[=] Kali NetHunter installed successfully

[*] Usage:
[+] nh | nethunter
[+]         Start NetHunter CLI.

[+] Use 'vnc' in NetHunter to launch VNC Server

[*] Login Information:
[*] User: kali
[*] Password: kali
[*] Visit https://github.com/jorexdeveloper/Install-NetHunter-Termux for documentation.
~ $ nethunter
nethunter: command not found

**Comment by jorexdeveloper** [comment]
Thanks for the heads up....i forgot to create ~/bin folder....now its fixed

**Comment by jorexdeveloper** [comment]
also....dont forget to add ~/bin to PATH for nh command to work
